baseURL = 'https://jakoblundoe.com'
languageCode = 'en-us'
title = 'JL-PORTFOLIO'
[params]
name = 'Jakob Lundoe'
[permalinks]
pages = "/:slug/"
[markup.goldmark.renderer]
unsafe = true
[security.node.permissions]
disable = true